### ISSUE TITLE
iOS 9 can't work with VolumeEvent.MUTE_STATE

### ISSUE THREAD

**Issue by ariesyxyx** [myflashlab/VolumePro-ANE#1]
Hello,

My iPhone 4s can't get VolumeEvent.MUTE_STATE when i switch silent button.
OS version is iOS 9.2.1

need help, thanks!

**Comment by myflashlab** [comment]
Have you put the comMyflashlabsVolumeMyExtension.caf file in a correct location?
https://github.com/myflashlab/VolumePro-ANE/tree/master/FD/bin

**Comment by ariesyxyx** [comment]
Yes, you got it!
Thanks a lot~
