### ISSUE TITLE
Questions...

### ISSUE THREAD

**Issue by lagommette** [myflashlab/VolumePro-ANE#10]
Hi,

I need to know which key that has been pressed. Is it possible without comparing previous volume level with actual volume level ?

- I do not want that the volume changes when I press on the keys. Is it possible to cancel the event ?
- What is the value of variable e when mute is on ?
- How do I switch mute on ? How do I switch mute off ?

Thanks in advance for your help.

Best regards,
lagommette

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
