### ISSUE TITLE
ios silent mode

### ISSUE THREAD

**Issue by kalashot** [myflashlab/VolumePro-ANE#11]
Hello!

I want to use VolumePro ANE in my game and NativeSound library works great! But I can't find any posibility to check if my ipad was muted off before the game started. So i can mute game sounds by listening VolumeEvent.MUTE_STATE only when iphone' physical button is switching off during the game running, and there is no chance to find out at the start of the game if the device is already in silent mode. Am I right? 

Thanks for your help

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
