### ISSUE TITLE
There is a problem with AIR 17

### ISSUE THREAD

**Issue by binhle12** [myflashlab/VolumePro-ANE#2]
VolumePro-ANE is so great.
But I have a problem. I'm using **AIR 17** to build the android app. Build successfully, however when I ran this app, I got `null exception` at method `Volume.init();`
So, what min air **version** does this ANE require?
Many thanks.

**Comment by myflashlab** [comment]
AIR 17 should be fine however, it's not recommended. Please try to compile with the latest AIR SDK always.
Nonetheless, the null error does not seem to be related to that at all. Are you trying to run your app on a simulator? if so, try it on a real device. Moreover, you may use our [inspector ANE](https://github.com/myflashlab/ANE-Inspector-Tool) to get more information about the reason that the init fails.
