### ISSUE TITLE
VolumeEvent.MUTE_STATE event got dispatched when the mute button hasn't been switched

### ISSUE THREAD

**Issue by jimmymjing** [myflashlab/VolumePro-ANE#8]
Hello, I'm having 2 problems with VolumeEvent.MUTE_STATE event.

The first problem is that this event got dispatched quite slow, so I couldn't detect whether the user's device was muted on my game's loading screen.

The second problem is that this event dispatched multiple of times even though the physical mute button hasn't been switched and sometimes the e.param value is not correct...

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
