### ISSUE TITLE
ArgumentError: Error #3500: The extension context does not have a method with the name command

### ISSUE THREAD

**Issue by lagommette** [myflashlab/VolumePro-ANE#9]
Hi,

I am trying to implement your volume ANE lite version into my app but with no success. When I run my app from animateCC on my macbookpro I get an error.

What am I doing wrong or what do I have forgotten ?

Thanks in advance for your help

## Environment ##
* iOS Version:
* AIR SDK Version: 26
* app.xml:
    <extensions>
        <extensionID>com.myflashlab.air.extensions.volume</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    </extensions>

## Problem Description ##
```
ArgumentError: Error #3500: The extension context does not have a method with the name command.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.myflashlab.air.extensions.volume::Launcher/onVolumeTimer()
	at flash.utils::Timer/_timerDispatch()
	at flash.utils::Timer/tick()
```
## Steps to Reproduce ##
Your github example...

```actionscript
import com.myflashlab.air.extensions.volume.Volume;
import com.myflashlab.air.extensions.volume.VolumeEvent;

Volume.init();

// you may use the Volume.value getter/setter to read and write know volume values. it must be a number between 0 and 1

// It is VERY important to Volume.dispose(); or at least remove the listener when you're closing your app
Volume.service.addEventListener(VolumeEvent.VOLUME_CHANGE, onDeviceVolumeChanged);

function onDeviceVolumeChanged(e:VolumeEvent):void
{
	trace("volume = " + e.param);
}

// you can also set a listener to know when the device goes silenced and when it comes back to normal
// It is VERY important to Volume.dispose(); or at least remove the listener when you're closing your app
Volume.service.addEventListener(VolumeEvent.MUTE_STATE, onDeviceMuteChanged);

function onDeviceMuteChanged(e:VolumeEvent):void
{
	trace("is device mute? " + e.param);
}

// And finally, you can listen to possible error messages which may happen on iOS side.
Volume.service.addEventListener(VolumeEvent.ERROR, onError);

function onError(e:VolumeEvent):void
{
	trace("onError = " + e.param);
}
```
## Known Workarounds ##
None

**Comment by myflashlab** [comment]
Errors like ```The extension context does not have a method with the name....``` usually happen if you are testing on a simulator. Try using a real device and you should be fine.

Also, such errors happen if the ANE is not correctly implemented in your project. If so, these videos might be helpful to you: https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by lagommette** [comment]
Hi, 


thanks for your help. I can now use your ANE. 


But I am still facing issues: 


- I need to know the tkey that has been pressed. Is it possible ? 
- I do not want that the volume changes when I press on the keys. Is it possible to cancel the event ? 
- In fact I whish to attach the keys to some other task. I wish to be able to maintain the key down and that it trigers the event until I release the key. Is it possible ? 


thanks in advance for your help. 


Best regards, 
Nicolas 

----- Mail original -----

De: "MyFlashLabs" <notifications@github.com> 
À: "myflashlab/VolumePro-ANE" <VolumePro-ANE@noreply.github.com> 
Cc: "lagommette" <nicolas.rossignol@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 9 Novembre 2017 06:22:05 
Objet: Re: [myflashlab/VolumePro-ANE] ArgumentError: Error #3500: The extension context does not have a method with the name command (#9) 


Errors like The extension context does not have a method with the name.... usually happen if you are testing on a simulator. Try using a real device and you should be fine. 
Also, such errors happen if the ANE is not correctly implemented in your project. If so, these videos might be helpful to you: https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by lagommette** [comment]
Hi, 


One more question, what is the value of e when mute is on ? 


thanks in advance for your help. 


Best regards, 
Nicolas 

----- Mail original -----

De: "Nicolas ROSSIGNOL" <nicolas.rossignol@free.fr> 
À: "myflashlab/VolumePro-ANE" <reply@reply.github.com> 
Cc: "Author" <author@noreply.github.com>, "myflashlab/VolumePro-ANE" <VolumePro-ANE@noreply.github.com> 
Envoyé: Mardi 21 Novembre 2017 22:31:06 
Objet: Re: [myflashlab/VolumePro-ANE] ArgumentError: Error #3500: The extension context does not have a method with the name command (#9) 


Hi, 


thanks for your help. I can now use your ANE. 


But I am still facing issues: 


- I need to know the tkey that has been pressed. Is it possible ? 
- I do not want that the volume changes when I press on the keys. Is it possible to cancel the event ? 
- In fact I whish to attach the keys to some other task. I wish to be able to maintain the key down and that it trigers the event until I release the key. Is it possible ? 


thanks in advance for your help. 


Best regards, 
Nicolas 

----- Mail original -----

De: "MyFlashLabs" <notifications@github.com> 
À: "myflashlab/VolumePro-ANE" <VolumePro-ANE@noreply.github.com> 
Cc: "lagommette" <nicolas.rossignol@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 9 Novembre 2017 06:22:05 
Objet: Re: [myflashlab/VolumePro-ANE] ArgumentError: Error #3500: The extension context does not have a method with the name command (#9) 


Errors like The extension context does not have a method with the name.... usually happen if you are testing on a simulator. Try using a real device and you should be fine. 
Also, such errors happen if the ANE is not correctly implemented in your project. If so, these videos might be helpful to you: https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by lagommette** [comment]
Hi,


thanks for your help. I can now use your ANE.


But I am still facing issues:


- I need to know which tkey that has been pressed. Is it possible without comparing previous volume level with actual volume level ?
- I do not want that the volume changes when I press on the keys. Is it possible to cancel the event ?
- In fact I whish to attach the keys to some other task. I wish to be able to maintain the key down and that it trigers the event until I release the key. Is it possible ?
- what is the value of variable e when mute is on ?
- How do I switch mute on ? How do I switch mute off ?

thanks in advance for your help.


Best regards,
lagommette

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
